# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('housetype', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('totalPrice', models.CharField(max_length=255)),
                ('followInfo', models.CharField(max_length=255)),
                ('unitPrice', models.CharField(max_length=255)),
                ('acreage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fangzi',
            },
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw', models.CharField(max_length=30)),
                ('cat', models.IntegerField(choices=[(1, '区域'), (2, '居室'), (3, '总价格'), (4, '面积')], default=1)),
                ('status', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '查询关键词',
                'verbose_name_plural': '查询关键词',
            },
        ),
    ]
